services:
  dev:
    build: .
    container_name: angular-itau-exam-app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - api
    ports:
      - 4200:4200

  api:
    build: .
    container_name: json-server-mock-api
    command: npx json-server --watch -p 3210 --host 0.0.0.0 business.json
    ports:
      - 3210:3210

volumes:
  node_modules: {}
